modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="tritia"
version="${file.jarVersion}"
displayName="Example Mod"
logoFile="tritia.png"
credits="Thanks to Silent Chaos for the forge tutorials"
authors="marcaçal2015"
description='''
mod
'''

[[dependencies.tritia]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tritia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
